### PR TITLE
Added Portuguese translation (pt-pt & pt-br)

### PR DESCRIPTION
**Pull request by Armfoot**
Translated all translatable strings to Portuguese (based on the Spanish `strings.xml` structure).

Alternative names (European and Brazilian Portuguese) were checked and added based on Wikipedia and Portuguese dictionaries.

### CODE REVIEW

**Comment by lkobus** [comment]
Its already released?

**Comment by brunoalreis** [comment]
I am from Portugal. Great work @Armfoot 
There are some possible improvements. For example, in the following translation no need to keep the ounce because is not used in Portugal nor in Brazil. it is just a preciosity, is not wrong.

`    <string-array name="food_info_serving_sizes_beverages_imperial">
        <item>340 g (12 onças)</item>
    </string-array>
`

Hope see this released soon.

Here is a screenshot from emulator:

screenshot_1546992893

**Comment by Armfoot** [comment]
> There are some possible improvements. For example, in the following translation no need to keep the ounce because is not used in Portugal nor in Brazil. it is just a preciosity, is not wrong.
> 
> ` <string-array name="food_info_serving_sizes_beverages_imperial"> <item>340 g (12 onças)</item> </string-array>`
>

Thank you for your comments Bruno. I thought about that issue before, but the thing is, that particular string refers to [imperial units](https://en.wikipedia.org/wiki/Imperial_units#Mass_and_weight) and all other languages' translations keep the "ounces" reference (in Romanian, for example, the [translation was not provided](https://github.com/nutritionfactsorg/daily-dozen-android/blob/51d273153f8b05d4809a09c17e170c3909ba4158/app/src/main/res/values-ro/strings.xml#L601)).

I added the approximate conversion in grams, just for Portuguese speakers having a better reference. However, if you notice the code below that line, there's already a [metric units string](https://github.com/nutritionfactsorg/daily-dozen-android/blob/51d273153f8b05d4809a09c17e170c3909ba4158/app/src/main/res/values-pt/strings.xml#L587) for the same purpose. So perhaps, it's better to keep the ounces reference (just for consistency with the other languages).

In any case, thank you for pointing it out and I will consider and edit other improvements if you notice better translations for them!

**Comment by brunoalreis** [comment]
There is one translation wrong.

<string name="history">História</string>

The right translation for history is Histórico. História is, for example, Peter Pan history book (livro da história do Peter Pan).

Behind that seems to be all ok. Good work

**Comment by Armfoot** [comment]
> The right translation for history is Histórico.

This string literally "escaped" me. All the other references to history were previously translated to _Histórico_ as well.

Nicely spotted Bruno. Obrigado!

**Comment by slavick** [comment]
@Armfoot Thank you for the translation!

**Pull request merged**
