### PR TITLE
values-zh

### PR DESCRIPTION
**Pull request by ikyli**
[values-zh.zip](https://github.com/nutritionfactsorg/daily-dozen-android/files/1368264/values-zh.zip)

### CODE REVIEW

**Comment by alibitek** [comment]
@ikyli Thanks for contributing a Chinese translation! However, this pull request is not correctly done.

You need to create a Git branch starting from the v15 branch (or you can commit directly in your v15 branch)
Then you need to overwrite the strings.xml from app/src/main/res/values-zh
Commit your changes
Push your commit to  the server, in branch you are on (a feature branch or the v15 branch, if you decided to stay with that)
Submit a pull request to merge that branch to v15 branch, not to master branch.

It's the task of the maintainer of this repository to merge v15 into branch not ours.

**Comment by alibitek** [comment]
The russian and chinese translations from v15 branch are affected by issue #82 and need to be corrected.

**Comment by alibitek** [comment]
The changes made to the values-zh/strings.xml seem to be invalid, [see this comment](https://github.com/nutritionfactsorg/daily-dozen-android/issues/67#issuecomment-335582764).

**Comment by slavick** [comment]
This pull request is outdated at this point. I am closing this now as the Chinese translation has been added to the app.

**Pull request closed without merging**
