### PR TITLE
Omega 3

### PR DESCRIPTION
**Pull request by lucivpav**
I have added an Omega 3 daily intake. DHA and EPA are essential Omega 3 fats that are only present in fish and algae. I believe that those who don't eat fish should know about this topic. For more information: https://nutritionfacts.org/topics/omega-3-fatty-acids/

### CODE REVIEW

**Comment by senpl** [comment]
from https://nutritionfacts.org/topics/omega-3-fatty-acids/
> Our body can then take that short-chain omega-3 and elongate it into the long-chain omega-3s EPA and DHA found in fish fat. 
So no supplementation seem to be required from my understanding.

**Comment by jpritikin** [comment]
@senpl See https://nutritionfacts.org/video/should-vegans-take-dha-to-preserve-brain-function/

Also, I think Dr Greger mentioned in a recent live q&a that we only need DHA because the body can easily convert DHA to EPA. However, I don't have a citation.

**Comment by senpl** [comment]
Still from https://nutritionfacts.org/topics/omega-3-fatty-acids/

> According to two of the most credible nutrition authorities, the World Health Organization and the European Food Safety Authority, we should get at least a half a percent of our calories from the short-chain omega-3 ALA. That’s easy: My Daily Dozen recommendation for one tablespoon of ground flaxseeds takes care of that. Our body can then take that short-chain omega-3 and elongate it into the long-chain omega-3s EPA and DHA found in fish fat.

So from my understanding if You take grounded flexseeds you do not need supplement DHA (as long as our body can convert short-chain amino acids into DHA).

**Comment by jpritikin** [comment]
See the supplement appendix in the 2015 book, "According to two of the most credible nutrition authorities, the World Health Organization and the European Food Safety Authority, you should get at least a half a percent of your calories from the short-chain omega-3 ALA.40 That’s easy—the one Daily Dozen tablespoon of ground flaxseeds takes care of that. Your body can then take the short-chain omega-3 from flaxseeds (or chia seeds or walnuts) and elongate it into the long-chain omega-3s EPA and DHA found in fish fat. The question, however, is whether the body can make enough for optimal brain health.41,42 Until we know more, I recommend taking 250 mg of pollutant-free long-chain omega-3s directly."

**Comment by senpl** [comment]
@lucivpav I think it should be named plant-based Omega 3, omega 3 from fish source is probably not recommended.

**Comment by senpl** [comment]
I prefer "non-animal omega 3 with DHA" because one from yeast are also recommended and maybe in future there will be other.

**Comment by inad9300** [comment]
"Omega 3" would be the best label. If someone wants more information, there will be a link to NutritionFacts.org as for the other cases. "Vitamin B12" is already handled in this way, i.e. the type is not clarified, and this is the best way, or else the app will start losing its beautiful simplicity.

I would also suggest the pill icon to be green, which can remind of the algae source.

**Comment by vrockai** [comment]
Doesn't flax seed cover the omega 3 requirements (ALA)?

**Comment by jpritikin** [comment]
> Doesn't flax seed cover the omega 3 requirements (ALA)?

No, see https://nutritionfacts.org/video/should-vegans-take-dha-to-preserve-brain-function/

**Comment by slavick** [comment]
@lucivpav I wanted to say thanks for the PR. I know it's been a while since you wrote this, but we're now in the process of updating the app.

I merged your PR, but my squash operation seems to have removed your contributor info from the history. I'm sorry, but I'm not sure how to fix it. I will gladly update it if you happen to know how.

**Pull request closed without merging**
