### PR TITLE
Improve German translation

### PR DESCRIPTION
**Pull request by caugner**
- Fixes typos.
- Fixes misleading/wrong translations.
- Improves punctuation.
- Improves understandability.
- Harmonizes form of address ("du" instead of "Sie").

### CODE REVIEW

**Comment by slavick** [comment]
@caugner In the next version I am adding checkboxes for Vitamin B12 and Vitamin D. Can you tell me if the following translations I got from Google are correct for German? I ask because it appears to be English to me =). 

```
<string name="vitamin_b12">Vitamin B12</string>
<string name="vitamin_d">Vitamin D</string>
```

Thanks!

**Comment by caugner** [comment]
@slavick Yes, they are correct.

**Comment by slavick** [comment]
@caugner Hello again. I have one last translation question before I wrap up the next version. Here are the strings in English:

```
    <string name="vitamin_divider_text">Vitamins</string>
    <string name="dialog_vitamin_explanation_text">Vitamin B12 and Vitamin D are essential for your health but do not count towards your daily servings.\n\nThey are included in this app to provide you with an easy way to track your intake.</string>
```

Here is what Google Translate gave me. Does it look correct?

```
    <string name="vitamin_divider_text">Vitamine</string>
    <string name="dialog_vitamin_explanation_text">Vitamin B12 und Vitamin D sind essentiell für Ihre Gesundheit, aber zähle nicht auf Ihre täglichen Portionen.\n\nSie sind in dieser App enthalten, um Ihnen eine einfache Möglichkeit, Ihre Aufnahme zu verfolgen.</string>
```

Thanks!

**Comment by caugner** [comment]
`Vitamin B12 und Vitamin D sind äußerst wichtig für deine Gesundheit, zählen aber nicht nicht zu den täglichen Portionen.\n\nSie sind in dieser App enthalten, damit du einfach den Überblick über deine Vitaminzufuhr behalten kannst.`

**Comment by slavick** [comment]
Great, thanks!

**Pull request merged**
