### PR TITLE
Polish version based on english & german version

### PR DESCRIPTION
**Pull request by senpl**
My translation of app. I based it on translating from english version. I also added required strings and structures to match that in german translation files. Translations is based on Wikipedia and all online searches.
Warning... I started this translation in 2017 and updated it to changes up to now, I tried to update all changes, but it is possible that some keys are translated based on old keys(I did my best to find all the changes, but mistakes happens).
If more informations or changes are needed let me know.
Thanks for all great work.

### CODE REVIEW

**Comment by marc-medley** [comment]
@senpl The Daily Dozen translation process for both the Android and Apple platforms has been relocated to a common repository [nutritionfactsorg/daily-dozen-localization](https://github.com/nutritionfactsorg/daily-dozen-localization).  

The [daily-dozen-localization](https://github.com/nutritionfactsorg/daily-dozen-localization) process has the following features:

* allows for translations to be submitted as Tab Separated Value (TSV) spreadsheets 
* supports concurrent translation coordination for both Android and Apple platforms
* is coordinated with/by the [Nutrition Facts Translation Team](https://nutritionfacts.org/volunteer/)
* supports key cross-mapping and coverage analysis between all Android/Apple/TSV source files 
* is being streamlined to support a larger number of translations (current planned estimate 40+ languages)
* has checks and reporting for review of human TSV input. For example: translation missing, translation same as english, and white space trimming.

> ... but it is possible that some keys are translated based on old keys

The utility that I've implemented for auto-generating Android `strings.xml` and Apple `*.xliff/*.strings/*.json` files from the TSV translation submission does a coverage check of the TSV keys against the latest Android/Apple sources keys.

So, TSV submissions will have a automatic full check and reporting of key coverage (added, dropped, changed).

A Polish translation for both platforms is currently in process and about 97% complete. See, ["Polish: translation submitted #4"](https://github.com/nutritionfactsorg/daily-dozen-localization/issues/4). You are welcome to review the submission and provide feedback for consideration by @Hangur and others.

Regarding, timeline for an Android Polish `strings.xml` generated from the TSV files for @slavick to review ... an autogenerated version Polish `strings.xml` and key coverage report is expected to be posted by tomorrow ... with later updates occurring based on activity in the ["Polish: translation submitted #4"](https://github.com/nutritionfactsorg/daily-dozen-localization/issues/4) comments thread.

**Comment by senpl** [comment]
Informations about moved localization repository should be on readme or contribution guidelines. Just to not waste contributors time.

**Comment by marc-medley** [comment]
@senpl Good point to have the readme/contribution guidelines refer to the translation repository. Will do. No intent to have anyone's time wasted. Thanks for your feedback.

**Comment by marc-medley** [comment]
@senpl A pull request ["Polish Translation with some correlated Android/Apple updates #166"](https://github.com/nutritionfactsorg/daily-dozen-android/pull/166), which contains the [translation you worked on with @Hangur](https://github.com/Hangur), has been created.

As always, your feedback is welcome. If you see no issues with PR#166, then this PR would be OK to close.

_Thank you for your efforts to help us with a Polish translation for both the Android and Apple platforms._

**Comment by slavick** [comment]
Thank you @senpl and @marc-medley! I've merged https://github.com/nutritionfactsorg/daily-dozen-android/pull/166 so I am closing this PR.

**Pull request closed without merging**
