### PR TITLE
greek translation fixes

### PR DESCRIPTION
**Pull request by kapcom01**
Here are some fixes for the greek translation.

### CODE REVIEW

**Comment by slavick** [comment]
In the next version I am adding checkboxes for Vitamin B12 and Vitamin D. Can you tell me if the following translations I got from Google are correct?

```
<string name="vitamin_b12">Βιταμίνη B12</string>
<string name="vitamin_d">Βιταμίνη D</string>
```

Thanks!

**Comment by kapcom01** [comment]
Yes. The tranlations about the vitamins B12 and D are correct.
Thanks for merging my translations btw.

**Comment by slavick** [comment]
@kapcom01 Hello again. I have one last translation question before I wrap up the next version. Here are the strings in English:

```
    <string name="vitamin_divider_text">Vitamins</string>
    <string name="dialog_vitamin_explanation_text">Vitamin B12 and Vitamin D are essential for your health but do not count towards your daily servings.\n\nThey are included in this app to provide you with an easy way to track your intake.</string>
```

Here is what Google Translate gave me. Does it look correct?

```
    <string name="vitamin_divider_text">Βιταμίνες</string>
    <string name="dialog_vitamin_explanation_text">Η βιταμίνη Β12 και η βιταμίνη D είναι απαραίτητες για την υγεία σας, αλλά δεν μετράνε για τις καθημερινές σας μερίδες.\n\nΠεριλαμβάνονται σε αυτήν την εφαρμογή για να σας παρέχουν έναν εύκολο τρόπο παρακολούθησης της πρόσληψής σας.</string>
```

Thanks!

**Comment by kapcom01** [comment]
The phrase "μετράνε για τις" should be "προσμετρώνται στις".

Here is the correct translation:
```
    <string name="vitamin_divider_text">Βιταμίνες</string>
    <string name="dialog_vitamin_explanation_text">Η βιταμίνη Β12 και η βιταμίνη D είναι απαραίτητες για την υγεία σας, αλλά δεν προσμετρώνται στις καθημερινές σας μερίδες.\n\nΠεριλαμβάνονται σε αυτήν την εφαρμογή για να σας παρέχουν έναν εύκολο τρόπο παρακολούθησης της πρόσληψής σας.</string>

```

**Comment by slavick** [comment]
Great, thanks!

**Pull request merged**
